[package]
name = "ros"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
x86_64 = "0.14.2"
spin = "0.10.0"
volatile = "0.2.6"
