[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-ros.json"
rustflags = [
	"-C", "overflow-checks=no"
]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
#runner = "./run.sh"